/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.awt.Font;
import javax.swing.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import borderRadius.roundedBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import java.util.ArrayList;
import BUS.HoaDonBUS;
import DTO.HoaDonDTO;
import GUI_Input.insertHoaDon;
import GUI_Input.deleteHoaDon;
import GUI_Input.updateHoaDon;
import GUI_Input.detailHD_promax;
import GUI_Input.timKiemNangCaoHoadon;
/**
 *
 * @author mhoang
 */
public class hoadonGUI extends javax.swing.JPanel {

    /**
     * Creates new form listCTKM
     */
    DefaultTableModel model = new DefaultTableModel();

    
    public hoadonGUI() {
        initComponents();
        headerTable();
        docSQL();
    }
    

    
    public void headerTable()
    {
        
        
        Vector header = new Vector();
        header.add("Mã hóa đơn");
        header.add("Ngày lập");
        header.add("Mã nhân viên");
        header.add("Mã khách hàng");
        header.add("Tổng tiền");
        model = new DefaultTableModel(header,0);
        tbHoadon.setModel(model);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // Căn nội dung ra chính giữa
        for (int i = 0; i < tbHoadon.getColumnCount(); i++) {
        tbHoadon.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
}

        //căn header ra center
        JTableHeader headerTB = tbHoadon.getTableHeader();
        DefaultTableCellRenderer center = (DefaultTableCellRenderer) headerTB.getDefaultRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        headerTB.setFont(new Font("Segoe UI",Font.BOLD,14));
    }
    public void docSQL()
    {
        model.setRowCount(0);
        HoaDonBUS bus = new HoaDonBUS();
        bus.docDSHD();
        for(HoaDonDTO ct : HoaDonBUS.ds)
        {
            Vector row = new Vector();
            row.add(ct.getMahd());
            row.add(ct.getNgaylap());
            row.add(ct.getManv());
            row.add(ct.getMakh());
            row.add(ct.getTongtien());
            model.addRow(row);
        }
        tbHoadon.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnExcel1 = new javax.swing.JButton();
        cbTim = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnLoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoadon = new javax.swing.JTable();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBorder(new roundedBorder(15)
        );

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addIcon.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.setToolTipText("");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deleteIcon.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setToolTipText("");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editIcon.png"))); // NOI18N
        btnUpdate.setText("SỬA");
        btnUpdate.setToolTipText("");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/detailIcon.png"))); // NOI18N
        btnDetail.setText("CHI TIẾT");
        btnDetail.setToolTipText("");
        btnDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refreshIcon.png"))); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.setToolTipText("");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnExcel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        btnExcel1.setText("XUẤT EXCEL");
        btnExcel1.setToolTipText("");
        btnExcel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcel1ActionPerformed(evt);
            }
        });

        cbTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tìm theo mã hóa đơn", "Tìm theo ngày lập", "Tìm theo mã nhân viên", "Tìm theo mã khách hàng", "Tìm theo tổng tiền" }));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnLoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filter.png"))); // NOI18N
        btnLoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRefresh)
                        .addComponent(btnExcel1)
                        .addComponent(btnDetail)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoa))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdate)
                                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoc))
                        .addGap(25, 25, 25)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tbHoadon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoadon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    // Gọi thư mục inputCTKM.java để điền info
    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        insertHoaDon dialog = new insertHoaDon(topFrame, true);
        dialog.setVisible(true);

        if (dialog.xacNhanNhap()) {
            HoaDonDTO hd = dialog.getHoaDon();

            HoaDonBUS bus = new HoaDonBUS();
            bus.them(hd);

            // Đọc lại dữ liệu từ SQL
            docSQL();

            // Cập nhật lại bảng
            model.setRowCount(0);
            for (HoaDonDTO ct : HoaDonBUS.ds) {
                Vector row = new Vector();
                row.add(ct.getMahd());
                row.add(ct.getNgaylap());
                row.add(ct.getManv());
                row.add(ct.getMakh());
                row.add(ct.getTongtien());
                model.addRow(row);
            }
            tbHoadon.setModel(model);
        }
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:      

        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        deleteHoaDon dialog = new deleteHoaDon(topFrame, true);
        dialog.setVisible(true);
        
        int i = tbHoadon.getSelectedRow();
        if(i<0)
        {
            JLabel lbchonMaXoa = new JLabel("Vui lòng chọn mã để xóa");
           lbchonMaXoa.setFont(new Font("Segoe UI",Font.BOLD,16));
           JOptionPane.showMessageDialog(this, lbchonMaXoa,"Chọn mã cần xóa",JOptionPane.ERROR_MESSAGE);
           return;           
        }
        if(dialog.xacNhanXoa())
        {
            int ma = (int) tbHoadon.getValueAt(i, 0);
            HoaDonBUS bus = new HoaDonBUS();
            bus.xoa(ma);
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here
        
        int i=tbHoadon.getSelectedRow();
        int mahd = (int) tbHoadon.getValueAt(i,0);
        String ngaylap = tbHoadon.getValueAt(i, 1).toString();
        int manv = (int) tbHoadon.getValueAt(i, 2);
        int makh = (int) tbHoadon.getValueAt(i, 3);
        int tongtien = (int) tbHoadon.getValueAt(i, 4);
        
        HoaDonDTO hdct = new HoaDonDTO(mahd, ngaylap, manv, makh, tongtien);
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        updateHoaDon dialog = new updateHoaDon(topFrame,true,hdct);
        dialog.setVisible(true);
        
        if(dialog.xacNhanCapNhat())
        {
            HoaDonBUS bus = new HoaDonBUS();
            HoaDonDTO hddata = dialog.getHD();
            bus.capnhat(hddata);
            
            model.setValueAt(hddata.getNgaylap(), i, 1);
            model.setValueAt(hddata.getManv(), i, 2);
            model.setValueAt(hddata.getMakh(), i, 3);
            model.setValueAt(hddata.getTongtien(), i, 4);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tbHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoadonMouseClicked

    }//GEN-LAST:event_tbHoadonMouseClicked

    
    public void updateTB(ArrayList<HoaDonDTO> dskq)
    {
        model.setRowCount(0);
        for(HoaDonDTO hd : dskq)
        {
            Vector row = new Vector();
            row.add(hd.getMahd());
            row.add(hd.getNgaylap());
            row.add(hd.getManv());
            row.add(hd.getMakh());
            row.add(hd.getTongtien());
            model.addRow(row);
        }
        tbHoadon.setModel(model);
    }
    
    
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        docSQL();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        
        int i=tbHoadon.getSelectedRow();
        if(i<0)
        {
           JLabel lbMadetail = new JLabel("Vui lòng chọn mã để xem");
           lbMadetail.setFont(new Font("Segoe UI",Font.BOLD,16));
           JOptionPane.showMessageDialog(this, lbMadetail,"Chọn mã cần xóa",JOptionPane.ERROR_MESSAGE);
           return;           
        }
        
        int mahd = (int) tbHoadon.getValueAt(i, 0);
        String ngaylap = tbHoadon.getValueAt(i, 1).toString();
        int manv = (int) tbHoadon.getValueAt(i, 2);
        int makg = (int) tbHoadon.getValueAt(i, 3);
        int tongtien = (int) tbHoadon.getValueAt(i, 4);
        
        HoaDonDTO data = new HoaDonDTO(mahd, ngaylap, manv, makg, tongtien);
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        detailHD_promax dialog = new detailHD_promax(topFrame,true,data);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnExcel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcel1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        int i = cbTim.getSelectedIndex();
        String tim = txtSearch.getText().trim();
//        if(tim.isEmpty())
//        {
//            docSQL();
//            return;
//        }
        HoaDonBUS bus = new HoaDonBUS();
        ArrayList<HoaDonDTO> kq = bus.timKiemThuong(tim, i);
        updateTB(kq);
        if(kq.isEmpty())
        {
            String mess = "Không tìm thấy kết quả: " + tim + " trong dữ liệu";
            JLabel lbNull = new JLabel(mess);
            lbNull.setFont(new Font("Segoe UI",Font.BOLD,16));
            JOptionPane.showMessageDialog(this, lbNull,"Thông báo",JOptionPane.ERROR_MESSAGE);                
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        timKiemNangCaoHoadon dialog = new timKiemNangCaoHoadon(topFrame, true);
        dialog.setVisible(true);
        
        if(dialog.xacNhanTim())
        {
            ArrayList<HoaDonDTO> kq = dialog.getDS();
            updateTB(kq);
            
            if(kq.isEmpty())
            {
            String mess = "Không tìm thấy kết quả trong dữ liệu";
            JLabel lbNull = new JLabel(mess);
            lbNull.setFont(new Font("Segoe UI",Font.BOLD,16));
            JOptionPane.showMessageDialog(this, lbNull,"Thông báo",JOptionPane.ERROR_MESSAGE);                      
            }
        }
    }//GEN-LAST:event_btnLocActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnExcel1;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbTim;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHoadon;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}   
