/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI_Click;

/**
 *
 * @author mhoang
 */
import GUI_Click.ctkmhdGUI_Click;
import GUI_Click.ctkmspGUI_Click;
public class guiHienThictkm extends javax.swing.JDialog {

    /**
     * Creates new form guiHienThictkm
     */
    public boolean xacNhanCTKMSP,xacNhanCTKMHD;
    public guiHienThictkm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCTKMSP = new javax.swing.JButton();
        btnCTKMHD = new javax.swing.JButton();

        setTitle("Chọn danh sách CTKM");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tìm theo CTKMSP hoặc CTKMHD");
        jPanel1.add(jLabel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 50, 0));

        btnCTKMSP.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCTKMSP.setText("CTKMSP");
        btnCTKMSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCTKMSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTKMSPActionPerformed(evt);
            }
        });
        jPanel2.add(btnCTKMSP);

        btnCTKMHD.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCTKMHD.setText("CTKMHD");
        btnCTKMHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCTKMHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCTKMHDActionPerformed(evt);
            }
        });
        jPanel2.add(btnCTKMHD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCTKMSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTKMSPActionPerformed
        // TODO add your handling code here:
        xacNhanCTKMSP = true;
        dispose();
    }//GEN-LAST:event_btnCTKMSPActionPerformed

    private void btnCTKMHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCTKMHDActionPerformed
        // TODO add your handling code here:
        xacNhanCTKMHD = true;
        dispose();
    }//GEN-LAST:event_btnCTKMHDActionPerformed

    
    public boolean xacNhanCTKMSP()
    {
        return xacNhanCTKMSP;
    }
    public boolean xacNhanCTKMHD()
    {
        return xacNhanCTKMHD;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCTKMHD;
    private javax.swing.JButton btnCTKMSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
