/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI_Input;

import BUS.HoaDonBUS;
import BUS.ChiTietHoaDonBUS;
import BUS.PhienBanSanPhamBUS;
import BUS.SanPhamBUS;
import DTO.ChiTietHoaDonDTO;
import DTO.HoaDonDTO;
import DTO.PhienBanSanPhamDTO;
import DTO.SanPhamDTO;
import MSForm.msfMaNV;
import MSForm.msfMaKH;
import MSForm.msfMaSP;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.util.ArrayList;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author laptop
 */
public class ThemHoaDon extends javax.swing.JDialog {
    public boolean xacNhan = false;
    public HoaDonDTO hd;
    public ChiTietHoaDonDTO cthd;
    public ArrayList<ChiTietHoaDonDTO> dsCTHD = new ArrayList<>();
    public HoaDonBUS hdbus = new HoaDonBUS();
    private ArrayList<PhienBanSanPhamDTO> danhSachPhienBan = new ArrayList<>();
    /**
     * Creates new form ThemPhieuNhap
     */
    public ThemHoaDon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setupMaSPChangeListener();
        tMaHD.setText(String.valueOf(hdbus.getAI()));
        setupAutoCalculation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tMaNV = new javax.swing.JTextField();
        tMaKH = new javax.swing.JTextField();
        btnMoreMaNV = new javax.swing.JButton();
        btnMoreMaKH = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnThemPN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tMaHD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tMaSP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tSoLuong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tDonGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tThanhTien = new javax.swing.JTextField();
        cbxPhienBan = new javax.swing.JComboBox<>();
        btnMoreSP = new javax.swing.JButton();
        btnXoaCTPN = new javax.swing.JButton();
        btnThemCTPN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSP = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        tTongTien = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM HÓA ĐƠN");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Mã khách hàng");

        jLabel3.setText("Mã nhân viên:");

        btnMoreMaNV.setText("...");
        btnMoreMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreMaNVActionPerformed(evt);
            }
        });

        btnMoreMaKH.setText("...");
        btnMoreMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreMaKHActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnThemPN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemPN.setText("Thêm");
        btnThemPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPNActionPerformed(evt);
            }
        });

        jLabel4.setText("Mã hóa đơn:");

        tMaHD.setFocusable(false);

        jLabel5.setText("Mã sản phẩm:");

        jLabel6.setText("Số lượng:");

        jLabel7.setText("Phiên bản:");

        jLabel8.setText("Đơn giá:");

        jLabel10.setText("Thành tiền:");

        tThanhTien.setFocusable(false);

        cbxPhienBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPhienBanActionPerformed(evt);
            }
        });

        btnMoreSP.setText("...");
        btnMoreSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoreSPActionPerformed(evt);
            }
        });

        btnXoaCTPN.setText("Xóa sản phẩm");
        btnXoaCTPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTPNActionPerformed(evt);
            }
        });

        btnThemCTPN.setText("Thêm sản phẩm");
        btnThemCTPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCTPNActionPerformed(evt);
            }
        });

        tbSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sản phẩm", "Phiên bản", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSP.setColumnSelectionAllowed(true);
        tbSP.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbSP);
        tbSP.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel9.setText("Tổng:");

        tTongTien.setFocusable(false);

        jLabel11.setText("Đ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 42, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(btnThemPN, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnMoreSP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cbxPhienBan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(btnXoaCTPN)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnThemCTPN)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnMoreMaKH))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnMoreMaNV))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMoreMaNV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMoreMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(278, 278, 278)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemPN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemCTPN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoaCTPN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMoreSP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxPhienBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoreMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreMaNVActionPerformed
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        msfMaNV msfDialog = new msfMaNV(topFrame, true);
        msfDialog.setVisible(true);
        
        
        if(msfDialog.xacNhanChon())
        {
            int manv = msfDialog.getMANV();
            tMaNV.setText(String.valueOf(manv));
        }
    }//GEN-LAST:event_btnMoreMaNVActionPerformed

    private void btnMoreMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreMaKHActionPerformed
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        msfMaKH msfDialog = new msfMaKH(topFrame, true);
        msfDialog.setVisible(true);
        
        
        if(msfDialog.xacNhanTim())
        {
            int makh = msfDialog.getMaKh();
            tMaKH.setText(String.valueOf(makh));
        }
    }//GEN-LAST:event_btnMoreMaKHActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        xacNhan=false;
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPNActionPerformed
        // Validate inputs
        if(tMaNV.getText().isEmpty() || tMaKH.getText().isEmpty()){
            JLabel lbTBnull = new JLabel("Không được để trống!");
            lbTBnull.setFont(new Font("Segoe UI", Font.BOLD, 16));
            JOptionPane.showMessageDialog(this, lbTBnull, "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if employee ID exists
        if(new HoaDonBUS().ktraMaNV(Integer.parseInt(tMaNV.getText())) == false) {
            JLabel lbTBnull = new JLabel("Mã nhân viên không tồn tại!");
            lbTBnull.setFont(new Font("Segoe UI", Font.BOLD, 16));
            JOptionPane.showMessageDialog(this, lbTBnull, "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if supplier ID exists
        if(new HoaDonBUS().ktraMaKH(Integer.parseInt(tMaKH.getText())) == false) {
            JLabel lbTBnull = new JLabel("Mã khách hàng không tồn tại!");
            lbTBnull.setFont(new Font("Segoe UI", Font.BOLD, 16));
            JOptionPane.showMessageDialog(this, lbTBnull, "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if product list is empty
        if(dsCTHD.isEmpty()) {
            JLabel lbTBnull = new JLabel("Chưa có sản phẩm nào trong hóa đơn!");
            lbTBnull.setFont(new Font("Segoe UI", Font.BOLD, 16));
            JOptionPane.showMessageDialog(this, lbTBnull, "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Create HoaDon
            int manv = Integer.parseInt(tMaNV.getText());
            int makh = Integer.parseInt(tMaKH.getText());
            int tongTien = Integer.parseInt(tTongTien.getText());
            
            // Get current date
            java.time.LocalDateTime now = java.time.LocalDateTime.now();
            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String ngayNhap = now.format(formatter);
            
            // Create PhieuNhap object
            hd = new HoaDonDTO(0, ngayNhap, manv, makh, tongTien, 0);
            
            // Add to database via BUS
            HoaDonBUS hdBUS = new HoaDonBUS();
            
            // Initialize if null
            if (hdBUS.ds == null) {
                hdBUS.docDSHD();
            }
            
            boolean resultHD = hdBUS.them(hd);
            
            if(resultHD) {
                
                // Add all CTPN to database via BUS
                ChiTietHoaDonBUS cthdBUS = new ChiTietHoaDonBUS();
                boolean allSuccess = true;
                System.out.println("=== DANH SÁCH CHI TIẾT HÓA ĐƠN ĐƯỢC THÊM VÀO DATABASE ===");
                int count = 1;

                for(ChiTietHoaDonDTO item : dsCTHD) {
                    System.out.println("-- Chi Tiết Hóa Đơn #" + count + " --");
                    System.out.println("Mã hóa đơn: " + item.getMaHoaDon());
                    System.out.println("Mã sản phẩm: " + item.getMaSanPham());
                    System.out.println("Phiên bản: " + item.getMaPhienBan());
                    System.out.println("Số lượng: " + item.getSoLuong());
                    System.out.println("Đơn giá: " + item.getDonGia());
                    System.out.println("Thành tiền: " + item.getThanhTien());
                    System.out.println("--------------");
                    count++;
                    // Add to database via BUS
                    boolean resultCTHD = cthdBUS.them(item);
                    if(!resultCTHD) {
                        allSuccess = false;
                        break;
                    }
                    
                }
                
                if(allSuccess) {
                    JLabel lbTB = new JLabel("Thêm hóa đơn thành công!");
                    lbTB.setFont(new Font("Segoe UI", Font.BOLD, 16));
                    JOptionPane.showMessageDialog(this, lbTB, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    xacNhan = true;
                    dispose();
                } else {
                    JLabel lbTB = new JLabel("Lỗi khi thêm chi tiết hóa đơn!");
                    lbTB.setFont(new Font("Segoe UI", Font.BOLD, 16));
                    JOptionPane.showMessageDialog(this, lbTB, "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JLabel lbTB = new JLabel("Lỗi khi thêm hóa đơn!");
                lbTB.setFont(new Font("Segoe UI", Font.BOLD, 16));
                JOptionPane.showMessageDialog(this, lbTB, "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JLabel lbTB = new JLabel("Lỗi xảy ra: " + e.getMessage());
            lbTB.setFont(new Font("Segoe UI", Font.BOLD, 16));
            JOptionPane.showMessageDialog(this, lbTB, "Thông báo", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemPNActionPerformed

    private void btnMoreSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoreSPActionPerformed
        // TODO add your handling code here:
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        msfMaSP msfDialog = new msfMaSP(topFrame, true);
        msfDialog.setVisible(true);
        
        
        if(msfDialog.xacNhanTim())
        {
            int manv = msfDialog.getMaSP();
            tMaSP.setText(String.valueOf(manv));
        }
    }//GEN-LAST:event_btnMoreSPActionPerformed

    // Hàm kiểm tra sản phẩm đã tồn tại trong danh sách CTHD chưa
    private int findExistingProductIndex(int masp, int mapb) {
        for (int i = 0; i < dsCTHD.size(); i++) {
            ChiTietHoaDonDTO item = dsCTHD.get(i);
            if (item.getMaSanPham() == masp && item.getMaPhienBan() == mapb) {
                return i; // Trả về vị trí của sản phẩm đã tồn tại
            }
        }
        return -1; // Không tìm thấy
    }

    public String getTenSanPhamByMaSP(int masp) {
        String tenSP = null;
        SanPhamBUS spBUS = new SanPhamBUS();
        tenSP = spBUS.getTenSanPhamByMaSP(masp);
        return tenSP;
    }
    // Cập nhật phương thức btnThemCTPNActionPerformed
    private void btnThemCTPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCTPNActionPerformed
        // Validate inputs
        if(tMaSP.getText().isEmpty() || tSoLuong.getText().isEmpty() || tDonGia.getText().isEmpty()) {
            JLabel lbTBnull = new JLabel("Vui lòng điền đầy đủ thông tin sản phẩm!");
            lbTBnull.setFont(new Font("Segoe UI", Font.BOLD, 16));
            JOptionPane.showMessageDialog(this, lbTBnull, "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Get values from input fields
            int masp = Integer.parseInt(tMaSP.getText());
            
            // Lấy mapb từ phiên bản đã chọn trong ComboBox
            int mapb = 1; // Giá trị mặc định
            int selectedIndex = cbxPhienBan.getSelectedIndex();
            
            if (selectedIndex >= 0 && selectedIndex < danhSachPhienBan.size()) {
                mapb = danhSachPhienBan.get(selectedIndex).getMaPB();
                System.out.println("Đã chọn phiên bản: " + cbxPhienBan.getSelectedItem() + ", MaPB=" + mapb);
            } else {
                System.out.println("Không có phiên bản được chọn, sử dụng mapb mặc định = 1");
            }
            
            int mahd = Integer.parseInt(tMaHD.getText());
            int soLuong = Integer.parseInt(tSoLuong.getText());
            int donGia = Integer.parseInt(tDonGia.getText());
            int thanhTien = soLuong * donGia;
            
            // Set thanh tien field
            tThanhTien.setText(String.valueOf(thanhTien));
            
            // Kiểm tra xem sản phẩm đã tồn tại chưa
            int existingIndex = findExistingProductIndex(masp, mapb);
            
            if (existingIndex != -1) {
                // Sản phẩm đã tồn tại, cập nhật số lượng và thành tiền
                ChiTietHoaDonDTO existingItem = dsCTHD.get(existingIndex);
                int newSoLuong = existingItem.getSoLuong() + soLuong;
                int newThanhTien = existingItem.getThanhTien() + thanhTien;
                
                // Cập nhật thông tin
                existingItem.setSoLuong(newSoLuong);
                existingItem.setThanhTien(newThanhTien);
                
                System.out.println("Cập nhật sản phẩm đã tồn tại:");
                System.out.println("Mã sản phẩm: " + masp);
                System.out.println("Mã phiên bản: " + mapb);
                System.out.println("Số lượng mới: " + newSoLuong);
                System.out.println("Thành tiền mới: " + newThanhTien);
                
                JLabel lbTB = new JLabel("Đã cập nhật số lượng sản phẩm trong hóa đơn!");
                lbTB.setFont(new Font("Segoe UI", Font.BOLD, 16));
                JOptionPane.showMessageDialog(this, lbTB, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Sản phẩm chưa tồn tại, thêm mới
                cthd = new ChiTietHoaDonDTO(mahd, masp, mapb, soLuong, donGia, thanhTien);
                dsCTHD.add(cthd);

                System.out.println("Thêm sản phẩm mới:");
                System.out.println("Mã hóa đơn: " + cthd.getMaHoaDon());
                System.out.println("Mã sản phẩm: " + cthd.getMaSanPham());
                System.out.println("Mã phiên bản: " + cthd.getMaPhienBan());
                System.out.println("Số lượng: " + cthd.getSoLuong());
                System.out.println("Đơn giá: " + cthd.getDonGia());
                System.out.println("Thành tiền: " + cthd.getThanhTien());
                
                JLabel lbTB = new JLabel("Đã thêm sản phẩm mới vào hóa đơn!");
                lbTB.setFont(new Font("Segoe UI", Font.BOLD, 16));
                JOptionPane.showMessageDialog(this, lbTB, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            
            // Update tong tien
            updateTongTien();
            
            // Refresh table
            loadTableData();
            
            // Clear input fields
            clearInputFields();
            
        } catch (NumberFormatException e) {
            JLabel lbTBnull = new JLabel("Dữ liệu không hợp lệ!");
            lbTBnull.setFont(new Font("Segoe UI", Font.BOLD, 16));
            JOptionPane.showMessageDialog(this, lbTBnull, "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemCTPNActionPerformed

    private void btnXoaCTPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTPNActionPerformed
        // Check if a row is selected
        int selectedRow = tbSP.getSelectedRow();
        if (selectedRow == -1) {
            JLabel lbTB = new JLabel("Vui lòng chọn sản phẩm cần xóa!");
            lbTB.setFont(new Font("Segoe UI", Font.BOLD, 16));
            JOptionPane.showMessageDialog(this, lbTB, "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Remove from list
        dsCTHD.remove(selectedRow);
        
        // Update total amount
        updateTongTien();
        
        // Refresh table
        loadTableData();
        
        JLabel lbTB = new JLabel("Đã xóa sản phẩm khỏi hóa đơn!");
        lbTB.setFont(new Font("Segoe UI", Font.BOLD, 16));
        JOptionPane.showMessageDialog(this, lbTB, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnXoaCTPNActionPerformed

    private void cbxPhienBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPhienBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPhienBanActionPerformed
    public boolean xacNhanThem()
    {                   
        return xacNhan;
    }
    public HoaDonDTO getHD()
    {
        return hd;
    }
    // Helper method to update total price
    private void updateTongTien() {
        int total = 0;
        for (ChiTietHoaDonDTO item : dsCTHD) {
            total += item.getThanhTien();
        }
        tTongTien.setText(String.valueOf(total));
    }

    // Helper method to load data to table
    private void loadTableData() {
        String[] headerNames = {"Tên sản phẩm", "Phiên bản", "Số lượng", "Đơn giá", "Thành tiền"};
        Object[][] data = new Object[dsCTHD.size()][5];
        
        PhienBanSanPhamBUS pbBUS = new PhienBanSanPhamBUS();
        
        for (int i = 0; i < dsCTHD.size(); i++) {
            ChiTietHoaDonDTO item = dsCTHD.get(i);
            String tenSP = getTenSanPhamByMaSP(item.getMaSanPham());
            data[i][0] = tenSP;
            
            // Lấy thông tin phiên bản cho từng sản phẩm
            int mapb = item.getMaPhienBan();
            String pbInfo = String.valueOf(mapb); // Mặc định hiển thị mapb
            
            try {
                // Lấy danh sách phiên bản cho sản phẩm hiện tại
                ArrayList<PhienBanSanPhamDTO> pbList = pbBUS.getPhienBanByMaSP(item.getMaSanPham());
                
                // Tìm phiên bản phù hợp
                for (PhienBanSanPhamDTO pb : pbList) {
                    if (pb.getMaPB() == mapb) {
                        pbInfo = pb.getSize() + " - " + pb.getMau();
                        break;
                    }
                }
            } catch (Exception e) {
                // Nếu có lỗi, hiển thị mã phiên bản
                System.out.println("Lỗi khi lấy thông tin phiên bản cho sản phẩm " + item.getMaSanPham() + ": " + e.getMessage());
            }
            
            data[i][1] = pbInfo;
            data[i][2] = item.getSoLuong();
            data[i][3] = item.getDonGia();
            data[i][4] = item.getThanhTien();
        }
        
        tbSP.setModel(new javax.swing.table.DefaultTableModel(data, headerNames) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }
    private void calculateThanhTien() {
        try {
            // Get values from fields (default to 0 if empty)
            int soLuong = tSoLuong.getText().isEmpty() ? 0 : Integer.parseInt(tSoLuong.getText());
            int donGia = tDonGia.getText().isEmpty() ? 0 : Integer.parseInt(tDonGia.getText());
            
            // Calculate and set ThanhTien
            int thanhTien = soLuong * donGia;
            tThanhTien.setText(String.valueOf(thanhTien));
        } catch (NumberFormatException e) {
            // If input is not a valid number, set ThanhTien to 0
            tThanhTien.setText("0");
        }
    }

    // Helper method to clear input fields
    private void clearInputFields() {
        tMaSP.setText("");
        tSoLuong.setText("");
        tDonGia.setText("");
    }
    private void setupAutoCalculation() {
        // Add document listener for SoLuong field
        tSoLuong.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                calculateThanhTien();
            }
    
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                calculateThanhTien();
            }
    
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                calculateThanhTien();
            }
        });
        
        // Add document listener for DonGia field
        tDonGia.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                calculateThanhTien();
            }
    
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                calculateThanhTien();
            }
    
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                calculateThanhTien();
            }
        });
    }
    private void setupMaSPChangeListener() {
        tMaSP.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updatePhienBanOptions();
            }
    
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updatePhienBanOptions();
            }
    
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updatePhienBanOptions();
            }
        });
    }
    private void updatePhienBanOptions() {
        try {
            // Lấy mã sản phẩm từ tMaSP
            int masp = tMaSP.getText().isEmpty() ? 0 : Integer.parseInt(tMaSP.getText());
            
            // Gọi hàm getPhienBanByMaSP từ PhienBanSanPhamBUS
            PhienBanSanPhamBUS pbBUS = new PhienBanSanPhamBUS();
            
            // Lưu danh sách phiên bản vào biến của class
            danhSachPhienBan = pbBUS.getPhienBanByMaSP(masp);
            
            // Xóa tất cả các mục trong cbxPhienBan
            cbxPhienBan.removeAllItems();
            
            // Thêm các phiên bản vào cbxPhienBan với định dạng size-màu
            for (PhienBanSanPhamDTO pb : danhSachPhienBan) {
                String displayText = pb.getSize() + " - " + pb.getMau();
                cbxPhienBan.addItem(displayText);
                System.out.println("Đã thêm phiên bản: " + displayText + ", MaPB=" + pb.getMaPB());
            }
            
            // Nếu không có phiên bản nào, thêm thông báo
            if (danhSachPhienBan.isEmpty()) {
                cbxPhienBan.addItem("Không có phiên bản");
                System.out.println("Ô trống, không có giá trị nào để hiển thị.");
            }
        } catch (NumberFormatException e) {
            // Nếu mã sản phẩm không hợp lệ, xóa nội dung cbxPhienBan
            cbxPhienBan.removeAllItems();
            cbxPhienBan.addItem("Không có phiên bản");
            danhSachPhienBan.clear();
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnMoreMaKH;
    private javax.swing.JButton btnMoreMaNV;
    private javax.swing.JButton btnMoreSP;
    private javax.swing.JButton btnThemCTPN;
    private javax.swing.JButton btnThemPN;
    private javax.swing.JButton btnXoaCTPN;
    private javax.swing.JComboBox<String> cbxPhienBan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tDonGia;
    private javax.swing.JTextField tMaHD;
    private javax.swing.JTextField tMaKH;
    private javax.swing.JTextField tMaNV;
    private javax.swing.JTextField tMaSP;
    private javax.swing.JTextField tSoLuong;
    private javax.swing.JTextField tThanhTien;
    private javax.swing.JTextField tTongTien;
    private javax.swing.JTable tbSP;
    // End of variables declaration//GEN-END:variables
}
